#!/bin/sh
set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: barrister2go <package-name>"
    echo "Reads the IDL from stdin and outputs the .go file contents to the STDOUT"
    exit 1
fi


barrister -i | idl2go -i -s -p $1
